### ISSUE TITLE
C

### ISSUE THREAD

**Issue by guozhenduo** [guozhenduo/matics#10]
Bangyen,Can you write extension module in C language?

**Comment by bangyen** [comment]
No, but I can learn. What do you need me to write?

**Comment by guozhenduo** [comment]
Matrices

在 2020-07-09 04:23:44，"Bangyen Pham" <notifications@github.com> 写道：


No, but I can learn. What do you need me to write?

**Comment by guozhenduo** [comment]
It's need fast.

在 2020-07-09 04:23:44，"Bangyen Pham" <notifications@github.com> 写道：


No, but I can learn. What do you need me to write?
