### ISSUE TITLE
Matrix Class Instance Variables

### ISSUE THREAD

**Issue by bangyen** [guozhenduo/matics#15]
Why did you change the definition of `self.adim` back to `list(str(arr)).count('[')`? As a result, matrix addition and multiplication stops working.
A multiplication example:
```python
x = Matrix([1, 2])
y = Matrix([[1, 0], [0, 1]])
z = x * y
```
An addition example:
```python
x = Matrix([[1], [2]])
y = Matrix([[1], [0]])
z = x + y
```

**Comment by guozhenduo** [comment]
You know,The best way to count the bits of an array is to see how many it has '['.

在 2020-07-11 02:33:53，"Bangyen Pham" <notifications@github.com> 写道：


Why did you change the definition of self.adim back to list(str(arr)).count('[')? As a result, matrix addition and multiplication stops working.
A multiplication example:

x=Matrix([1, 2])
y=Matrix([[1, 0], [0, 1]])
z=x*y

An addition example:

x=Matrix([[1], [2]])
y=Matrix([[1], [0]])
z=x+y

**Comment by bangyen** [comment]
That's already counted using `self.length`.

**Comment by bangyen** [comment]
Just test the module and see for yourself that it doesn't work.

**Comment by guozhenduo** [comment]
Ooooooooo

在 2020-07-11 11:00:47，"Bangyen Pham" <notifications@github.com> 写道：


Just test the module and see for yourself that it doesn't work.
