### ISSUE TITLE
Fraction Class Functionality

### ISSUE THREAD

**Issue by bangyen** [guozhenduo/matics#17]
By taking the `gcd` of the arguments passed to the `Fraction` class, aren't you limiting the functionality of the class? Now, it's not possible to create a `Fraction` object with `float` arguments.

**Comment by guozhenduo** [comment]
Let me changed it.

在 2020-07-11 02:48:51，"Bangyen Pham" <notifications@github.com> 写道：


By taking the gcd of the arguments passed to the Fraction class, aren't you limiting the functionality of the class? Now, it's not possible to create a Fraction object with float arguments.

**Comment by guozhenduo** [comment]
No.Scores do not accept floating-point points.

在 2020-07-11 02:48:51，"Bangyen Pham" <notifications@github.com> 写道：


By taking the gcd of the arguments passed to the Fraction class, aren't you limiting the functionality of the class? Now, it's not possible to create a Fraction object with float arguments.

**Comment by guozhenduo** [comment]
>>> import fractions as f
>>> F = f.Fraction
>>> F(2.0,4.0)
Traceback (most recent call last):
  File "", line 1, in 
  File "/data/data/com.termux/files/usr/lib/python3.8/fractions.py", line 174, in __new__
    raise TypeError("both arguments should be "
TypeError: both arguments should be Rational instances
>>>

在 2020-07-11 02:48:51，"Bangyen Pham" <notifications@github.com> 写道：


By taking the gcd of the arguments passed to the Fraction class, aren't you limiting the functionality of the class? Now, it's not possible to create a Fraction object with float arguments.

**Comment by bangyen** [comment]
What I'm asking is: wouldn't it be nice to allow fractions to have non-integer numerators/denominators?

**Comment by guozhenduo** [comment]
Are you trying to say:
>>> import fractions as f
>>> F=f.Fraction
>>> d=F("1/3")

在 2020-07-11 10:59:25，"Bangyen Pham" <notifications@github.com> 写道：


What I'm asking is: wouldn't it be nice to allow fractions to have non-integer numerators/denominators?

**Comment by bangyen** [comment]
That would be a nice feature, and I sent you an email with an implementation of it; however, it is not what I'm talking about. What I'm trying to say is that `Fraction(1.5, 3)` should be allowed. That way, `Fraction(1.5, 3) * Fraction(2) == Fraction(1)`.
