### ISSUE TITLE
Suggestion: Matrix Class

### ISSUE THREAD

**Issue by bangyen** [guozhenduo/matics#2]
It might be interesting to implement a class that handles matrix math, e.g. addition, multiplication, and inverses.

**Comment by guozhenduo** [comment]
???

在 2020-07-06 17:06:12，"Bangyen Pham" <notifications@github.com> 写道：


It might be interesting to implement a class that handles matrix math, e.g. addition, multiplication, and inverses.

**Comment by guozhenduo** [comment]
I see.

在 2020-07-06 17:06:12，"Bangyen Pham" <notifications@github.com> 写道：


It might be interesting to implement a class that handles matrix math, e.g. addition, multiplication, and inverses.

**Comment by guozhenduo** [comment]
It should be implemented soon.
But there are more bugs😆.
That would require the numpy module(Python)
Wait till I get to know it.
Will you help me?
在 2020-07-06 17:06:12，"Bangyen Pham" <notifications@github.com> 写道：


It might be interesting to implement a class that handles matrix math, e.g. addition, multiplication, and inverses.
