### ISSUE TITLE
Annotation

### ISSUE THREAD

**Issue by guozhenduo** [guozhenduo/matics#21]
Let's write the annotation now.This will make the changes easy.

**Comment by bangyen** [comment]
Annotation? Do you mean code documentation in the form of comments? If so, it'd probably be neater to create a whole new file called `documentation.md` to store all documentation. Additionally, it might be nice to organize the repository files by adding more folders.

**Comment by guozhenduo** [comment]
OK.

在 2020-07-13 14:16:03，"Bangyen Pham" <notifications@github.com> 写道：


Annotation? Do you mean code documentation in the form of comments? If so, it'd probably be neater to create a whole new file called documentation.md to store all documentation. Additionally, it might be nice to organize the repository files by adding more folders.
