### ISSUE TITLE
Chinese

### ISSUE THREAD

**Issue by guozhenduo** [guozhenduo/matics#3]
Can you speak Chinese,Bangyen?

**Comment by guozhenduo** [comment]
And your email?

**Comment by guozhenduo** [comment]
I will start writing Matrix classes in August.

**Comment by bangyen** [comment]
I cannot speak Chinese, unfortunately. My email is [bangyen99@gmail.com](mailto:bangyen99@gmail.com). If you ever find any bugs in your code, feel free to open a new issue here and [mention](https://github.blog/2011-03-23-mention-somebody-they-re-notified/) me.

**Comment by guozhenduo** [comment]
I see.
