### ISSUE TITLE
Reform

### ISSUE THREAD

**Issue by guozhenduo** [guozhenduo/matics#6]
I'm going to transform the password project into an interpreter.

**Comment by guozhenduo** [comment]
Do you know re(A Python module)?

**Comment by bangyen** [comment]
I do; what do you mean by interpreter?

**Comment by guozhenduo** [comment]
for instance

**Comment by guozhenduo** [comment]
"(-(|)=(@)=(~)=(~)=(~)-)"will be interpreted as "print('a')"

**Comment by guozhenduo** [comment]
"(-(|)=(&)=(~)=(~)=(~)-)"will be interpreted as "print('a')"
